# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d851345d1a574cf4e3fc10b7f5a831fafefe4e838b0543ca0182dc0c9f2830e56c4ca04ef60cfef0632ddfda325eb99a8e7e78bffe0911e56098aa28007f4685

test:
  secret_key_base: 1cb75e7f11a352934cd2cd2418c0e71f57ddecf4b0ee0593ea373905412b835f96f2acec9a1c2d5308c2729d3bdec297b5da8ccd3add88a5dc02b8ef674da7e0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
